export const SELECT_TOOL = 'SELECT_TOOL';
export const SELECT_BRUSH = 'SELECT_BRUSH';
export const SET_BRUSH_OPACITY = 'SET_BRUSH_OPACITY';
export const SET_BRUSH_SIZE = 'SET_BRUSH_SIZE';
export const SET_CAMERA_ACTIVE = 'SET_CAMERA_ACTIVE ';
export const SELECT_COLOR = 'SELECT_COLOR';
export const SELECT_ZOOM = 'SELECT_ZOOM';
export const SELECT_LAYER = 'SESSION_ERROR';
export const GESTURE_MODE = 'GESTURE_MODE';
export const IS_DRAWING = 'IS_DRAWING';
export const SET_START_HAND_POSE_DETECTION = "SET_START_HAND_POSE_DETECTION"; 
export const SET_CLEAR_CANVAS = "SET_CLEAR_CANVAS"; 
export const SET_PAINTING_REF = 'SET_PAINTING_REF';

export const VOICE_CONTROL_STATUS = 'VOICE_CONTROL_STATUS';
export const VOICE_CONTROL_MODE_CONTROL = 'VOICE_CONTROL_MODE_CONTROL';
export const IS_CHANGE_HAND_COLOR = 'IS_CHANGE_HAND_COLOR';

export const RESET_STATE = 'RESET_STATE';

